### ISSUE TITLE
live cd is 480, drive install is 240

### ISSUE THREAD

**Issue by sharpfork** [substring/os#1]
- Iso released on Easter
- instal type: 'generic-15Khz' instal
- rig: i5 4690k. ATI 5450, ntsc crt tv

syslinux
``append root=/dev/disk/by-label/GA rw quiet rd.udev.log-priority=3 splash mitigations=off audit=0 monitor=generic_15 video=VGA-2:320x240S``

GA splash, AM, GAsetup, all 240
live CD/USB has GA splash, AM, GAsetup, all 480 as expected

Thanks for all that hard work!

**Comment by substring** [comment]
Hey :)

This was fixed by a re-release of iso. I had forgotten to tag and bump gatools
