### ISSUE TITLE
Two queries

### ISSUE THREAD

**Issue by mapaupuropo** [substring/os#11]
1) How is the PC2Jamma adapter configured? for an arcade jamma to recognize the commands?

2) I tried using groovyarcade on a PC with pentium 4 2.8ghz and it says that it is not compatible with i686, it only requires 64 bit processor to work?

Thanks!!!

**Comment by substring** [comment]
Hi !

1. PC2jamma : not supported anymore, works on a parallel port, this is way outdated
2. P4 : we're in 2021, 21bits is dead, you need a 64bits processor

**Comment by mapaupuropo** [comment]
Thanks for the answer, do you remember which was the last version that was compatible with PC2Jamma? I want to take advantage of the hardware that I have.

**Comment by substring** [comment]
Needs the openppjoy kernel module which is like 10 years old, I'm not even sure it still compiles on the current kernel. Otherwise, check the "legacy" groovyarcade form VeS, on the arcacontrols forum.

Then, depending on your linux skills, we can try to build it and test it
