### ISSUE TITLE
Dual Boot ?

### ISSUE THREAD

**Issue by deadl0ck** [substring/os#13]
Hi,
If I chose to install this to my hard drive does it wipe it or does it give the option to dual boot it (I have windows already on it) ?
I don't want to check in case I select the option and then it proceeds to wipe the HD totally...
If there is no dual boot option it would be a nice enhancement to have if possible,
Thanks all !

**Comment by substring** [comment]
Hi,

The installer totally wipes the hard drive. If you want to dual boot, I strongly recommend you use 2 hard drives.

**Comment by deadl0ck** [comment]
Thanks - I'll close this
