### ISSUE TITLE
Does groovyarcade boot at 15khz?

### ISSUE THREAD

**Issue by wolfshow** [substring/os#16]
Anything need to do to protect the CRT?

**Comment by substring** [comment]
As I said last time, this place is for issues. If you have questions, join the discord or ask over at BYOAC.

Unless you flash your video card bios, PCs boot at 31kHz minimum, up to you to manage that, this is beyond what GA can do. When booting GA, you're aked which Horizontal frequency you'd wish (but this screen is still at 31kHz unless you flashed your vbios). Then GA will run at the expected Hfreq.
