### ISSUE TITLE
Joystick quirks support

### ISSUE THREAD

**Issue by juniorterin** [substring/os#17]
V-USB twin joystick (based on ATMEGA microchips) doesn't seems to be supported in Arch distro. Ubuntu based SO's works fine following this steps https://retropie.org.uk/forum/topic/24408/juyao-dual-arcade-2-player-on-ubuntu/15

In GA only the first player works

Link to driver > http://vusb.wikidot.com/project:mamepanel

**Comment by substring** [comment]
Closing since there have been no replies for a year
