### ISSUE TITLE
Can't boot in 15khz after install

### ISSUE THREAD

**Issue by zombizF** [substring/os#18]
GroovyArcade 2022.01
--> OK to install it on a SSD with a LCD screen or in 15khz mode... but after reboot i'm then unable to boot in 15khz (so black screen on my arcade CRT), and the "change display" setup doesn't work... GroovyArcade 2022.01 works OK on a LCD though...

As a workaround, is it possible to force the ouptut though a script / setup file ?

**Comment by substring** [comment]
First of all, hello, it's always good to start a message that way.

Then, based on what you're saying, I have absolutely no useful information of what is going wrong, how I could help and so. So the easiest would be that you start with your LCD plugged, quit attract mode, and in the gasetup text menu, go to troubleshoot > send logs and give me the URL.

**Comment by zombizF** [comment]
Hi,
(You're right, it's better to begin like that :))

Tried again with a fresh install, same result unfortunately :(  (LCD install, trying to boot to 15khz Arcade CRT)

The logs are here:
https://transfer.sh/mkt4i8/ga-support.tar.zst

**Comment by substring** [comment]
You're not using the install procedure the right way. GroovyArcade detected a monitor on DVI-I that looks like a LCD, so it did not configure anything like 15kHz. How could it know where your CRT is plugged if you didn't plug it ? You may anyway boot the install ISO with both screens connected. If you can't connect both at the same time, just highlight the expected boot menu you need, swap monitors, press ENTER, and follow the setup process. But never swap the CRT connector, this is mandatory. I suppose your CRT will be on on your DVI-I port. So:

- `sudo nano /boot/syslinux/syslinux.cfg`
- when you see `video=DVI-I-1:` add 640x480iS so it looks like `video=DVI-I-1:640x480iS`
- Press CTRL+X, say Yes twice
- reboot by typing `reboot`
- plug your CRT before it starts GroovyArcade

**Comment by zombizF** [comment]
OK thanks.
The mistake i made was to swap LCD with CRT in the wrong timing, and then force the CRT setting in the menu thinking it would force the output... but it was not designed that way.
So i reinstalled Groovy Arcade once again, using only the CRT (15khz) and this way the installation correctly autodected the CRT.
Thanks for your help @substring and keep up with your almighty work, Groovy Arcade is great !
