### ISSUE TITLE
Insert Environment variables correctly?

### ISSUE THREAD

**Issue by MrMEEE** [substring/os#19]
I have earlier created issue #4 ...

I seems like there is now a fix available: 
https://github.com/libsdl-org/SDL/pull/4727/commits/02a6ff0da0272c2ec2f1dd2629924848f33cb40a
https://github.com/libsdl-org/SDL/commit/1c78b0800759174abe1bac01ce5b9cd788a6a372

I need to set the environment variable: SDL_LINUX_JOYSTICK_CLASSIC=1

Where do I set that in GrooveArcade, so that everything will read this variable?

**Comment by substring** [comment]
Edit /home/arcade/.bash_profile so it looks like;
```bash
#!/bin/bash
SDL_LINUX_JOYSTICK_CLASSIC=1
if [[ $(tty) == /dev/tty1 ]] ; then
    sudo setterm -powerdown 0 -powersave off -blank 0
    /opt/galauncher/startfe.sh
    sudo gasetup
fi
```
(just one line to add)
This doesn't fix your issue, it just uses a different joystick driver

**Comment by MrMEEE** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  HiThanks for the feedback..Why don't you think it will fix my issue? The /dev/input/js* devices are always in the right order.. The events ones are not??Is there something I'm not seeing?                                                                                                                                             Sendt fra min BlackBerry - den sikreste mobilenhed                                                                                                                                                                           Fra: ***@***.***: 22. februar 2022 21.23Til: ***@***.*** til: ***@***.***: ***@***.***; ***@***.***: Re: [substring/os] Insert Environment variables correctly? (Issue #19)  
Edit /home/arcade/.bash_profile so it looks like;
#!/bin/bash
SDL_LINUX_JOYSTICK_CLASSIC=1
if [[ $(tty) == /dev/tty1 ]] ; then
    sudo setterm -powerdown 0 -powersave off -blank 0
    /opt/galauncher/startfe.sh
    sudo gasetup
fi
(just one line to add)
This doesn't fix your issue, it just uses a different joystick driver

**Comment by substring** [comment]
The email reply was totally messed up ...

If it fixes your issue, fine.

**Comment by MrMEEE** [comment]
Well.. It did something.. 

Seems like it has stabilized the names of the joysticks.. 

One weird thing, though.. they are now mapped in this way:

Real Joy1 -> Attracts Joy0
Real Joy2 -> Attracts Joy1
Real Joy3 -> Attracts Joy2
Real Joy0 -> Attracts Joy3

The /dev/input/js* are still mapped correctly..

Do you have any reason why these joysticks are remapped inside attract? (maybe it counts from 1?)

**Comment by MrMEEE** [comment]
Hmmm.. seems like it was random... 

an "export" needs to be added infront of the environment variables to make it active in .bash_profile...

Now, using "export SDL_LINUX_JOYSTICK_CLASSIC=1" just disables to joysticks..

Using the gamepad-tool utility, I have figured out that I get the correct mapping if I use: "export SDL_JOYSTICK_DISABLE_UDEV=1".. but if I add that to .bash_profile, the joysticks are also disabled??

Any clues?

**Comment by substring** [comment]
have you tried forcing the devices order ? see https://github.com/libsdl-org/SDL/issues/4430#issuecomment-867653888. I can see you've been posting on the SDL repo for your problem. All in all it sounds related to udev. But the joystick API is supposed to be deprecated is is still here for retro compatibility purpose ...

**Comment by MrMEEE** [comment]
https://github.com/libsdl-org/SDL/issues/4688 gives me a fix for MAME.. but not for Attract Mode, as that is written in SFML and not SDL... 

https://github.com/SFML/SFML/issues/2033

**Comment by substring** [comment]
Remap all joysticks in AM

**Comment by substring** [comment]
Original problem answered, the rest is specific to some libs
