### ISSUE TITLE
mouse pointer disappears

### ISSUE THREAD

**Issue by AkiAfroo** [substring/os#2]
when i start the lxde desktop a second time the mouse pointer disappears

to return it I have to change to attract mode, then exit and start gasetup and change the frontend to lxde then it appears again

**Comment by substring** [comment]
Hi !

This is due to the `--nocursor` flag passed to startx on some shells, not some others. I've started working on working this all over. One of the chages would be not to consider LXDE as a front end, but as something that can be started from gasetup (instead of the text file browser). This may evetually reach the May iso release.

**Comment by AkiAfroo** [comment]
yep, i saw the --nocursor option in gasetup code and i will wait for may release. one more thing i want to comment and i dont want to open a second issue here i go:
1.-i dont know if  the distro include a option to mount usb / external drive but  i always have to install udiskie and gvfs could be nice to have it by default in the future.
2.-i tried your last retrofe compiled and cant display the videos preview in my test machine but same machine with ubuntu i can see those preview videos come with the layout/themes
to be more expecify im "building CoinOps" in groovy and have couple of issues with retrofe that you compiled and kind share with us here
https://github.com/substring/packages/releases
i tried your version and official one and got the same issue about show the videos maybe is something related to codecs.

thnx in advance for all the work done!

**Comment by substring** [comment]
1. sure will do. I'm also thinking about how to automount a usb drive that would have a few expected folders.

2. haven't tried retrofe, I guess it's missing some libs. Reading https://bitbucket.org/phulshof/retrofe/src/default/#markdown-header-compiling-and-installing-on-ubuntu-linux-1004-or-newer points to gstreamer, which IS installed with retrofe. Not top priority issue tbh

**Comment by AkiAfroo** [comment]
ok, i fixed retrofe installing gstreamer-base

**Comment by substring** [comment]
I'm working on setting up retrofe, and videos are indeed a problem. There is no gstreamer-base package, could you check what you've installed ?
