### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by mingkosan** [substring/os#20]
is a long time can't update anything

**Comment by substring** [comment]
yeah my bad, , I missed an option in the updates. You have to manually `sudo pacman -Syu` to fully update.

What version of gasetup do you have ? (`pacman -Q gasetup`)

**Comment by mingkosan** [comment]
thanks, I am install 2022.01. I type sudo pacman -Syu in UXterm. but it display "groovyarcade-testing.db is faied to download error: failed receieving file groovyarcade-testing.db  from github.com : ssl certicate problem certificateis not yet calid
error:failed to synchronize all databass download library error"

**Comment by substring** [comment]
Looks like your system date is not right, you can check it with `date`. You may configure locale + time synchronization in gasetup > system > system setup >language/keyboard > autodetect both

**Comment by mingkosan** [comment]
Finally, well, I set the date in the BIOS to the correct one. Now it can be updated. Thank you very much. I like this system very much and hope it can become better.
