### ISSUE TITLE
Disable/Configure Switchres

### ISSUE THREAD

**Issue by MrMEEE** [substring/os#3]
Hi

I'm trying to use GroovyArcade together with my PC-JAMMA board ( http://www.bartoxsystems.com/?page_id=48 )

The arcade cabinet uses a K7000 monitor, and I have chosen that in the installation..

I have the menu working, but when I startup a game, I get a black screen, and it then exits to the (gasetup) menu.. I think it's because switchres changes to something else that the supported resolutions on the PC-JAMMA board (640x480, 800x600, 1024x768, 720x400)..

I get this in the logs:

SwitchRes: [supertnk] (1) vertical (256x256@50.000000)->(456x256@50.000000)
Switchres: xrandr resolution switch error, original mode restored
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0xc00014
  Serial number of failed request:  238
  Current serial number in output stream:  250
2021-01-05 22:50:01 - make_action(52): INFO - Starting emulators/groovymame.sh->post_launch
2021-01-05 22:50:01 - post_launch(22): INFO - Postlaunching mame
2021-01-05 22:50:01 - make_action(52): INFO - Starting modules/cpu_governor.sh->post_launch
2021-01-05 22:50:01 - post_launch(22): INFO - Restoring CPU governor to schedutil
2021-01-05 22:50:01 - make_action(52): INFO - Starting modules/ledspicer.sh->post_launch
2021-01-05 22:50:01 - post_launch(19): INFO - Postlaunching ledspicer. Args: arcade supertnk
2021-01-05 22:50:01 - post_launch(26): DBG  - Service not running.... exiting
The requested video mode is not available, switching to a valid mode
Failed to get output info for.primary monitor position
Failed to get output info for fullscreen mode, switching to window mode
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
The requested video mode is not available, switching to a valid mode
Failed to get output info for.primary monitor position
Failed to get output info for fullscreen mode, switching to window mode

Is there a way to disable switchres or reconfigure it to use the supported resolutions??

I have tried using the LCD configuration, but doesn't really seem to change anything...

**Comment by substring** [comment]
Hi,

Can you paste your mame.ini somewhere ? GroovyMame (GM) switches to resolutions that are computed on your monitor setting. The file is located in /home/arcade/shared/configs/mame/mame.ini

can you also give me the result of `cat /proc/cmdline` ?

**Comment by MrMEEE** [comment]
Hi

It's completely standard:
https://pastebin.com/b1SvdxP7

[root@GroovyArcade arcade]# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-linux-15khz root=/dev/disk/by-label/GA rw quiet rd.udev.log-priority=3 splash mitigations=off audit=0 monitor=k7000 video=720x400 edd=off  initrd=/initramfs-linux-15khz.img

**Comment by substring** [comment]
Well I'm a little astonished :
  * `video=720x400` will most probably give a 1024x768 resolution anyway as you're not using 15kHz modes we've added in the kernel
  * seems you've tried a vertical game, same problem with horizontal games ? or Your screen is vertical ?
  * yes switchres does change the resolution to fit the original one as good as possible. And my intuition tells me that your pc-jamma board doesn't like it

Can you elaborate a bit more on your full rig ? CPU, GFX card, how your GFX card is connected to your PC-JAMMA board (honnestly, a J-PAC is way better).

**Comment by MrMEEE** [comment]
Well.. the PC-JAMMA board actually does what the "hacked" kernel does.. It doesn't need any special modes.. it just needs an input of 640x480, 800x600, 1024x768 or 720x400, and then it outputs 15kHz...

Doesn't really seem to matter if I use a vertical or horizontal game.. (screen is horizontal)...

Isn't there a way to completely turnoff switchres? (I have tried switchres=0 in mame, but no luck)..

The machine is a small Asus media center, with a Core2Duo and an onboard Intel card.. the card is connected to the PC-JAMMA board with HDMI..

**Comment by substring** [comment]
Technically speaking, you don't need GroovyArcade if you don't use the 15kHz kernel features or switchres 😉 The whole point is to play arcade games at their native resolution, not something stretched to 4 possible resolutions. This means screen resolution but also refresh rate. We do aim at perfect video accuracy, which won't happen with your rig.

That said, I'm not sure about the setting to disable modeswitching, try `modeline_generation`. I'll get a solution once home, I'm no mame expert.

Now, the modeswitching probably fails because of the low dotclock that is not supported with your Intel iGPU. Usually they work better with a 25MHz minimum dotclock. And Intel GPUs have awful tearing sadly, their vsync just sucks.

**Comment by MrMEEE** [comment]
I know.. I chose GroovyArcade because I like the menu...

actually, modeline_generation=0 works :)...

Thanks a lot...

**Comment by substring** [comment]
Nice, I'm closing then. If you ever update to groovymame 227, the option name may have changed. It's in the testing repo for now + need to fix some upgrade stuff.

**Comment by MrMEEE** [comment]
I actually tried to update, but afterwards the attract gui wouldn't start?.. do you have an update guide?

**Comment by substring** [comment]
just `pacman -S sfml` to get rid of sfml-git and restore sflm. I'll remove the package from the stable repo soon, at the same time GM 227 goes to stable
