### ISSUE TITLE
Groovyarcade fails to load AM after update

### ISSUE THREAD

**Issue by retrorepair** [substring/os#30]
So I've fresh installed GA as I changed hardware and all went well, everything seemed to work just fine. Then I did a system update through the setup menu and updated and downloaded the retroarch cores and performed a reboot, now I get the attached.

It's still booting, I can access the samba share, but I have a feeling it's now got a problem outputting to the correct display.

Is there something I can do to fix this? I check the groovy log file but there's no entry from this boot. Subsiquent reboots don't help.

Attached is my ga.conf, it looks correct to me. I've got VGA out via a dvi to vga adapter on the only output with analog support. I also have 75ohm resistors to gnd on the rgb to force the edid which it seems to require (on this card and the previous hd 5450).

Hardware is:
I5 3550
8gb ddr3
Gtx 650
![16814619292051877551792219944690](https://user-images.githubusercontent.com/38870678/231993157-492cefcc-ad3c-40fc-a497-55857157138e.jpg)

**Comment by retrorepair** [comment]
somehow managed to make the picture the link to the conf file so if you click that you'll see it!

**Comment by retrorepair** [comment]
Not sure what you mean by boot a progressive 25mhz edid? Like I say, it worked absolutely fine before the update.

I was under the impression nvidia worked well with super resolutions under linux.

I was hoping to use it to help with 3d based games in retro arch as it's much faster than my 5450. Maybe I'll just have to revert back.

**Comment by substring** [comment]
There us quite a leap between the iso and today between kernel and switchres updates. So it's hard to tell which one is at fault here.

Try connecting with SSH, run `sudo gasetup` znd run the troubleshoot option and send the final link please

**Comment by retrorepair** [comment]
Ok, here's the link:

https://transfer.sh/bD7pUL/ga-support.tar.zst

**Comment by substring** [comment]
Logs lok weird. There is no trace of the installation itself, so I don't know what settings were applied. I can see you're using 1280x480i as a resolution, which is 25MHz interlaced, not progressive. So it could be that interlaced was removed with Kernel upgrade, I can't tell.

All in all, no resolution is reported to be ctive on an GFX card connector

So what we may try is :
- use a progressive resolution -> ass root, edit /boot/syslinux/syslinux.cfg and replace 1280x480 by 1280x240 (keep everything that is around), but I'm afraid it won't work
- use an EDID instead of the in-built kernel resolution -> a little trickier, we'll see after the 1st test

**Comment by retrorepair** [comment]
I'll try that shortly. FYI though, all I've done is install GA, add mame roms via samba, update and thats it

**Comment by retrorepair** [comment]
![Screenshot_20230414_165853_JuiceSSH](https://user-images.githubusercontent.com/38870678/232095932-abed5d92-36ca-4cd1-9d8e-7254761061c4.jpg)

This is how I edited it, hopefully I didn't mess it up. I hate using Vim type editors, makes no sense to me :)

It's still the same though :(

**Comment by substring** [comment]
Ok, so edit (with nano, it's easier) and replace `video=DVI-I-1:1280x240S` with `video=DVI-I-1:e drm.edid_firmware=edid/eneric_15_super_resp.bin`

**Comment by retrorepair** [comment]
Ok, well that's worked.. kinda. It does now boot on the right screen and loads attract mode, but hsync is way out of spec for both (see pics).

I managed to load world rally though and it looks fine so I think it's just a case of getting the modeline for the UI correct :)
![20230414_191603](https://user-images.githubusercontent.com/38870678/232126009-6b326288-2920-422a-a15b-0bea7e1c0c3a.jpg)
![20230414_191652](https://user-images.githubusercontent.com/38870678/232126023-60cab665-c3b9-4103-987c-aab600e4e401.jpg)
![20230414_191728](https://user-images.githubusercontent.com/38870678/232126043-43313e89-ed11-4ca4-99bd-2fd6e8f4ec0a.jpg)

**Comment by retrorepair** [comment]
It seems c-sync being enabled in Atom15 doesn't play well with the GA environment. I made the change and all is well.

**Comment by substring** [comment]
Csync is not supported
