### ISSUE TITLE
I am update full,but I can't enter to the frontend

### ISSUE THREAD

**Issue by mingkosan** [substring/os#32]
i can run groovymame in desktop and it is 0.254,but can't enter to am frontend,and i want install pegasus-frontend,bu it is can't install success.

**Comment by substring** [comment]
Please run `sudo gasetup -n attract 2.6.2-8 3.0.0-1`

**Comment by mingkosan** [comment]
Welcome to Groovy Arcade Linux Setup
cp: target '/root/shared/frontends/attract/': No such file or directory
sed: can't read /root/shared/frontends/attract/attract.cfg: No such file or directory
sed: can't read /root/shared/frontends/attract/attract.cfg: No such file or directory

Maybe I made a mistake updating it.

**Comment by mingkosan** [comment]
I can chose grooymame or retroarch frontend,just am not to use

**Comment by substring** [comment]
Don't run as root that command, run it as arcade

**Comment by mingkosan** [comment]
sorry,I am reinstall,but update finally,it hanve 27 files need to download,But when it is downloaded, it prompts
error: linux-api-headers: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/linux-api-headers-6.3-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
I enter Y,nd then the system deleted the file，and prompts
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
Repeat this way

**Comment by mingkosan** [comment]
gcc-libs-13.1.1-...    35.2 MiB  15.2 MiB/s 00:02 [######################] 100%
 groovymame-extra-0.253-1-any is up to date
 attractplus-3.0.1-1-any is up to date
 glibc-2.37-3-x86_64     9.9 MiB  16.4 MiB/s 00:01 [######################] 100%
 binutils-2.40-5-...     7.5 MiB  15.4 MiB/s 00:00 [######################] 100%
 groovymame-tools-0.254-1-x86_64 is up to date
 zsh-5.9-3-x86_64        2.2 MiB  11.5 MiB/s 00:00 [######################] 100%
 broadcom-wl-15khz-6.30.223.271-465-x86_64 is up to date
 db-6.2.32-1-x86_64   1360.3 KiB  8.00 MiB/s 00:00 [######################] 100%
 sdl2-2.26.5-2-x86_64 is up to date
 db5.3-5.3.28-2-x...  1229.3 KiB  7.85 MiB/s 00:00 [######################] 100%
 linux-api-header...  1226.3 KiB  8.37 MiB/s 00:00 [######################] 100%
 attractplus-x11-3.0.1-1-any is up to date
 attractplus-kms-3.0.1-1-any is up to date
 libical-3.0.16-4...   614.2 KiB  4.61 MiB/s 00:00 [######################] 100%
 gasetup-1.12.0-1-any is up to date
 libldap-2.6.4-2-...   280.9 KiB  2.83 MiB/s 00:00 [######################] 100%
 libsasl-2.1.28-4...   147.5 KiB  1695 KiB/s 00:00 [######################] 100%
 switchres-2.0-10-x86_64 is up to date
 exfatprogs-1.2.0-1-x...    59.1 KiB  1182 KiB/s 00:00 [############################] 100%
 hidapi-0.13.1-2-x86_64     40.6 KiB   813 KiB/s 00:00 [############################] 100%
 gatools-0.3.3-1-any is up to date
 upd72020x-fw-20200826-4-any is up to date
 galauncher-0.2.6-1-any is up to date
 Total (27/27)              59.7 MiB  2.55 MiB/s 00:23 [############################] 100%
(430/430) checking keys in keyring                     [############################] 100%
(430/430) checking package integrity                   [############################] 100%
error: linux-api-headers: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/linux-api-headers-6.3-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]

**Comment by substring** [comment]
Update through gasetup, your arch keyring is outdated
