### ISSUE TITLE
Couldn't update the pacman database, aborting

### ISSUE THREAD

**Issue by retrorepair** [substring/os#35]
I get this message on a clean install after trying to change the frontend or do a system update which pretty much means I can't do a lot. Not much else to say.

I'm running a Gigabyte GA-H61M-S2PV and a Radeon HD 6570

**Comment by substring** [comment]
Hi

Have you tried updating through gasetup or manually ? If the layter, which commands have you typed ?

**Comment by retrorepair** [comment]
Through gasetup. I don't do anything manually unless I absolutely have to

**Comment by substring** [comment]
What is the complete output of `sudo pacman -Syu archlinux-keyring` ?

**Comment by retrorepair** [comment]
Apparently I didn't understand that changing the frontend requires an update which requires an internet connection. Apparently my router wasn't properly configured as a switch and while my server didn't mind, nothing else could access the internet. All sorted now.
