### ISSUE TITLE
About changing computers

### ISSUE THREAD

**Issue by mingkosan** [substring/os#37]
If you change to a new computer hardware, can it run without reinstalling the system?

**Comment by substring** [comment]
Depends on what you change in your PC + boot method (bios or uefi)

**Comment by substring** [comment]
"will not work" is too vague. What you probably have to do is at least regenerate the initramfs with `mkinitcpio -p linux-15khz` + edit the kernel command line to fit the right connector names. Please provide further info on what "will not work" means (can't boot ? no display ?)
