### ISSUE TITLE
Joysticks are switched around on reboot?

### ISSUE THREAD

**Issue by MrMEEE** [substring/os#4]
Hi

I have 4 connected joysticks in my arcade cabinet...

These are always detected as /dev/input/js{0,1,2,3} .. but within attract and mame they are often switched around on reboot...

(e.g player 1 becomes player 3 and so on)

This switch doesn't happen on device level, js0 is always player 1 if I use jstest..

How does this mapping work? Do they use some of the event devices?

**Comment by substring** [comment]
Hi!

forget about /dev/input/js{0,1,2,3}, that's the old deprecated joystick API. What matters is /dev/intput/eventXX

And I don't think you can force the order of devices here.

Can you provide the mame log part about your joysticks ? To enable verbose mode, start AM, press TAB, in Emulators/MAME, append `-v` to the command line The log is in `~/shared/logs.mame.log`

**Comment by MrMEEE** [comment]
Joystick: Start initialization
Input: Adding joystick #0: HID16c0:05df (device id: 03000000c0160000df05000001010000)
Joystick: HID 16c0:05df [GUID 03000000c0160000df05000001010000]
Joystick:   ...  2 axes, 8 buttons 0 hats 0 balls
Joystick:   ...  Physical id 0 mapped to logical id 1
Joystick:   ...  Does not have haptic capability
Input: Adding joystick #1: HID16c0:05df (device id: 03000000c0160000df05000001010000)
Joystick: HID 16c0:05df [GUID 03000000c0160000df05000001010000]
Joystick:   ...  2 axes, 8 buttons 0 hats 0 balls
Joystick:   ...  Physical id 1 mapped to logical id 2
Joystick:   ...  Does not have haptic capability
Input: Adding joystick #2: HID16c0:05df (device id: 03000000c0160000df05000001010000)
Joystick: HID 16c0:05df [GUID 03000000c0160000df05000001010000]
Joystick:   ...  2 axes, 8 buttons 0 hats 0 balls
Joystick:   ...  Physical id 2 mapped to logical id 3
Joystick:   ...  Does not have haptic capability
Input: Adding joystick #3: HID16c0:05df (device id: 03000000c0160000df05000001010000)
Joystick: HID 16c0:05df [GUID 03000000c0160000df05000001010000]
Joystick:   ...  2 axes, 8 buttons 0 hats 0 balls
Joystick:   ...  Physical id 3 mapped to logical id 4
Joystick:   ...  Does not have haptic capability
Joystick: End initialization

**Comment by MrMEEE** [comment]
The funny thing is, that the event devices also seem to be in the correct order...
[arcade@GroovyArcade shared]$ udevadm info /dev/input/js0
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input9/js0
N: input/js0
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick
S: input/by-id/usb-16c0_05df-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input9/js0
E: DEVNAME=/dev/input/js0
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: USEC_INITIALIZED=11610484
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_VENDOR=16c0
E: ID_VENDOR_ENC=16c0
E: ID_VENDOR_ID=16c0
E: ID_MODEL=05df
E: ID_MODEL_ENC=05df
E: ID_MODEL_ID=05df
E: ID_REVISION=0101
E: ID_SERIAL=16c0_05df
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2.1:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_2_1_1_0
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick /dev/input/by-id/usb-16c0_05df-joystick
E: TAGS=uaccess:seat
E: CURRENT_TAGS=uaccess:seat

[arcade@GroovyArcade shared]$ udevadm info /dev/input/js1
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input10/js1
N: input/js1
L: 0
S: input/by-id/usb-16c0_05df-joystick
S: input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input10/js1
E: DEVNAME=/dev/input/js1
E: MAJOR=13
E: MINOR=1
E: SUBSYSTEM=input
E: USEC_INITIALIZED=11599350
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_VENDOR=16c0
E: ID_VENDOR_ENC=16c0
E: ID_VENDOR_ID=16c0
E: ID_MODEL=05df
E: ID_MODEL_ENC=05df
E: ID_MODEL_ID=05df
E: ID_REVISION=0101
E: ID_SERIAL=16c0_05df
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2.1:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_2_1_1_0
E: DEVLINKS=/dev/input/by-id/usb-16c0_05df-joystick /dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick
E: TAGS=seat:uaccess
E: CURRENT_TAGS=seat:uaccess

[arcade@GroovyArcade shared]$ udevadm info /dev/input/js2
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input11/js2
N: input/js2
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick
S: input/by-id/usb-16c0_05df-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input11/js2
E: DEVNAME=/dev/input/js2
E: MAJOR=13
E: MINOR=2
E: SUBSYSTEM=input
E: USEC_INITIALIZED=11630252
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_VENDOR=16c0
E: ID_VENDOR_ENC=16c0
E: ID_VENDOR_ID=16c0
E: ID_MODEL=05df
E: ID_MODEL_ENC=05df
E: ID_MODEL_ID=05df
E: ID_REVISION=0101
E: ID_SERIAL=16c0_05df
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2.1:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_2_1_1_0
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick /dev/input/by-id/usb-16c0_05df-joystick
E: TAGS=uaccess:seat
E: CURRENT_TAGS=uaccess:seat

[arcade@GroovyArcade shared]$ udevadm info /dev/input/js3
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input12/js3
N: input/js3
L: 0
S: input/by-id/usb-16c0_05df-joystick
S: input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:16C0:05DF.0001/input/input12/js3
E: DEVNAME=/dev/input/js3
E: MAJOR=13
E: MINOR=3
E: SUBSYSTEM=input
E: USEC_INITIALIZED=11613910
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_VENDOR=16c0
E: ID_VENDOR_ENC=16c0
E: ID_VENDOR_ID=16c0
E: ID_MODEL=05df
E: ID_MODEL_ENC=05df
E: ID_MODEL_ID=05df
E: ID_REVISION=0101
E: ID_SERIAL=16c0_05df
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2.1:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_1_0
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_2_1_1_0
E: DEVLINKS=/dev/input/by-id/usb-16c0_05df-joystick /dev/input/by-path/pci-0000:00:14.0-usb-0:2.1:1.0-joystick
E: TAGS=seat:uaccess
E: CURRENT_TAGS=seat:uaccess

In these last two infos, player2's joystick is recognized as player1..

**Comment by substring** [comment]
event ids are not in the same order I bet, forget js*

**Comment by MrMEEE** [comment]
They are actually are...

If you look at the DEVPATH lines.. these include the event id number (input*).. e.g. js3 is input12=event12..

**Comment by substring** [comment]
That is not a /dev/input/event* name. I guess the pads order depends on how SDL2 considers them, and I bet that at initialization, it uses an event id. Look at this example :
```$ udevadm info /dev/input/event27
P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/input/input38/event27
N: input/event27
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-joystick
S: input/by-id/usb-ZD___ZD_GAME_FOR_WINDOWS___00000000-event-joystick
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/input/input38/event27
E: DEVNAME=/dev/input/event27
E: MAJOR=13
E: MINOR=91
E: SUBSYSTEM=input
E: USEC_INITIALIZED=19154756457
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_VENDOR=ZD
E: ID_VENDOR_ENC=ZD
E: ID_VENDOR_ID=045e
E: ID_MODEL=__ZD_GAME_FOR_WINDOWS__
E: ID_MODEL_ENC=\x3c\x20ZD\x20GAME\x20FOR\x20WINDOWS\x20\x3e
E: ID_MODEL_ID=028e
E: ID_REVISION=0100
E: ID_SERIAL=ZD___ZD_GAME_FOR_WINDOWS___00000000
E: ID_SERIAL_SHORT=00000000
E: ID_TYPE=generic
E: ID_BUS=usb
E: ID_USB_INTERFACES=:ff5d01:ff5d03:ff5d02:ff5d04:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=xpad
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_0
E: ID_INPUT_JOYSTICK_INTEGRATION=internal
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_2_1_0
E: LIBINPUT_DEVICE_GROUP=3/45e/28e:usb-0000:00:14.0-2
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-joystick /dev/input/by-id/usb-ZD___ZD_GAME_FOR_WINDOWS___00000000-event-joystick
E: TAGS=:seat:snap_chromium_chromedriver:snap_chromium_chromium:uaccess:
```
See the difference ?

**Comment by MrMEEE** [comment]
I see.. so basically.. there is no way to solve this issue :( ??

**Comment by substring** [comment]
Can't tell, honestly. Should dig in SDL2 code, udev rules, or https://docs.mamedev.org/advanced/devicemap.html

**Comment by substring** [comment]
no feedback for a month, shall I close ?

**Comment by MrMEEE** [comment]
Sorry for leaving this for so long.. 
I have been trying a lot of things to get this working..
The link you provided above (Stable Controller IDs) only works if the joysticks are individual joysticks.. and not one device with multiple joystick.. (all having the same PID and VID).. 

Any ideas at all???
