### ISSUE TITLE
Monitor not being identified, black screen after bios

### ISSUE THREAD

**Issue by retrorepair** [substring/os#40]
I'm struggling with this, is there a hard and fast solution without adding resistors to the RG or B lines?

My monitor already has 75ohm impedance and any more resistance makes it too dark.

Is there not a way to force a monitor to be detected at all times?

**Comment by substring** [comment]
Hi

This monitor behaves like an arcade monitor then, and needs manual validation when GroovyArcade is testing all outputs with the "Press enter if you see this message". If you missed that, plug a lcd or use SSH, list the existing connectors in /sys/class/drm, find the one you need to activate in the syslinux.cfg with the syntax `video=<connector>:e`. For example with VGA-1 : `video=VGA-1:e`

**Comment by retrorepair** [comment]
Ah ok, I didn't think I'd missed that but guess I must have. Thanks, will give that a go.

**Comment by retrorepair** [comment]
Ok, it seems like it's already in the syslinux.cfg.

Video=DVI-I-1:640x480iS

The full name of the connector though according to the sys/class/drm tolder is card0-DVI-I-1 so is that exactly what should be in there? If so, how do I edit that file safely? I can get into  the desktop by jamming a low ohm resistor between red and gnd but don't know how best to do this.

**Comment by substring** [comment]
`video=DVI-I-1:640x480ieS`

Le dim. 19 nov. 2023 à 08:47, retrorepair ***@***.***> a
écrit :

**Comment by retrorepair** [comment]
I'll try that, thanks. What does the "e" do?

**Comment by retrorepair** [comment]
That did it, thank you 👍 I wonder if this should be default behaviour or a gasetup option?

**Comment by substring** [comment]
As I said, you missed the moment to press enter when GA is testing all connectors. If it requires a user input, it's because it couldn't guess by itself if there is a monitor connected

**Comment by retrorepair** [comment]
I don't think I did though, I remember doing it (only built this system a few weeks ago).

It asks you twice doesn't it? Pressed enter both times.

I feel like this has happened a few times in the past too

**Comment by retrorepair** [comment]
Reinstalled, think this was due to a system swap. Same gfx card and hdd, didn't realise it'd mean this would be an issue
