### ISSUE TITLE
updata error

### ISSUE THREAD

**Issue by mingkosan** [substring/os#41]
(70/70) checking keys in keyring                   [######################] 100%
warning: Public keyring not found; have you run 'pacman-key --init'?
downloading required keys...
The upgrade shows like this, what should I do? Is it still a network problem?
/var/cache/pacman/pkg in download 140 files,
sof-firmware-2023.09.2-1-x86_64.pkg.tar.zst
sof-firmware-2023.09.2-1-x86_64.pkg.tar.zst.sig
like this
I tried many times
I hope there is a package that integrates retroarch and fbneo,That would be much more convenient

**Comment by mingkosan** [comment]
ssh run sudo pacmane -Syu,I want to install retroarch and fbneo,It must be upgraded
There will always be various problems when upgrading this system. It would be great if the system integrates retroarch and fbneo

**Comment by mingkosan** [comment]
gtk-update-icon-...    17.4 KiB  4.69 KiB/s 00:04 [######################] 100%
 systemd-sysvcomp...     6.0 KiB  1668   B/s 00:04 [######################] 100%
 systemd-resolvco...     3.1 KiB   871   B/s 00:04 [######################] 100%
 systemd-254.6-2-...     7.7 MiB  86.9 KiB/s 01:31 [######################] 100%
 vim-runtime-9.0....     6.9 MiB  75.2 KiB/s 01:34 [######################] 100%
 smbclient-4.19.3...     6.7 MiB  70.3 KiB/s 01:38 [######################] 100%
 intel-ucode-2023...     5.8 MiB  59.6 KiB/s 01:40 [######################] 100%
 linux-firmware-2...   198.8 MiB   744 KiB/s 04:34 [######################] 100%
 linux-firmware-m...    61.2 MiB   195 KiB/s 05:21 [######################] 100%
 perl-5.38.1-1-x86_64   20.2 MiB  62.7 KiB/s 05:31 [######################] 100%
 Total (71/71)         415.2 MiB  1286 KiB/s 05:31 [######################] 100%
(71/71) checking keys in keyring                   [######################] 100%
(71/71) checking package integrity                 [######################] 100%
error: amd-ucode: signature from "Tobias Powalowski <tpowa@archlinux.org>" is un                   known trust
:: File /var/cache/pacman/pkg/amd-ucode-20231110.74158e7a-1-any.pkg.tar.zst is c                   orrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]

download and delete,always like this

**Comment by mingkosan** [comment]
Ok, I solved the problem, I need to initialize the keyring first

rm -rf /etc/pacman.d/gnupg
pacman-key --init
pacman-key --populate

and updata keyring

pacman -Sy archlinux-keyring

Finally the upgrade was successfully completed

**Comment by substring** [comment]
The missing keyring was fixed in the last ISO
