### ISSUE TITLE
If unplugged, GA installation on USB stick won't boot anymore

### ISSUE THREAD

**Issue by stimPowerRangers** [substring/os#43]
Hi,

If GroovyArcade 2023.11 installed on a USB, GA will boot successfully as long as the USB stick remains plugged.
If the GA installed USB stick is unplugged and replaced by another bootable USB key, then GA won't be able to boot anymore.

**Steps to reproduce:**
1. Install GA on a USB stick
2. Check that installed GA boots correctly
3. Unplug GA USB stick
4. Swap it by another bootable USB key
5. Power on PC
6. Shutdown
7. Replug the GA USB stick
8. Power on, the key won't boot anymore.

I got the same issue with  GroovyArcade 2022.01, GA 2019 works fine.

**Comment by substring** [comment]
Hi,

Very few people install GroovyArcade on a USB stick and it's not a method I'd recommend. U have a feeling you're on UEFI and not legacy bios. Can you confirm ?

**Comment by stimPowerRangers** [comment]
Hi,
Yes I confirm UEFI usage. Do you think that switching back to legacy bios would solve my issue ?
Although it's not conventional, it's very practical for me to install several 15khz distros on usb sticks for testing purposes and going back and forth.

Btw I thank you for your hard work! :+1:

**Comment by substring** [comment]
Sounds to me like a buggy NVRAM. So stick to BIOS if your mobo allows it. UEFI support was introduced in 2020 or 2021 in GA, can't remember

**Comment by stimPowerRangers** [comment]
I set Legacy mode everywhere possible in Bios options, and then reinstalled GA.
Now the behavior is what you'd expect : I can swap USB sticks 

Thanks for the help. :+1:
