### ISSUE TITLE
Issues after update (incompatible package versions?)

### ISSUE THREAD

**Issue by MrMEEE** [substring/os#44]
After updating both OS and Groovy i got the following missing files:

libsfml-graphics.so.2.5
libsfml-window.so.2.5
libsfml-system.so.2.5

This seems to have been caused by fml being updated to 2.6..

I have tried symlinking the files to their 2.6 versions, but then I get this issue:

attract: symbol lookup error: attract: undefined symbol: _ZN2sf6Window19setKeyRepeatEnabledEb

What to do?

**Comment by substring** [comment]
Why would you need these files ? nothing requires them unless you didn't accept replacing attract by attractplus

**Comment by MrMEEE** [comment]
hmmm.. I don't think that was asked about replacing attract with attractplus? how do I change to attractplus?

**Comment by substring** [comment]
try `sudo pacman -Sy attractplus`

**Comment by MrMEEE** [comment]
Do I need to remove attract?

**Comment by substring** [comment]
Yes you do

**Comment by MrMEEE** [comment]
I didn't get prompted.. 

So I ended up running:

pacman -Sy attractplus
pacman -R attract

and then I needed to add

FE=attractplus

to the /home/arcade/.xinitrc file
