### ISSUE TITLE
HELP!!! Cannot enter Front-end and Desktop after upgrade

### ISSUE THREAD

**Issue by mingkosan** [substring/os#45]
==> WARNING: Possibly missing firmware for module: 'ast'
  -> Running build hook: [autodetect]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
  -> Running build hook: [plymouth]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux-15khz.img'
==> Image generation successful
(14/22) Reloading system bus configuration...
(15/22) Warn about old perl modules
(16/22) Updating fontconfig cache...
(17/22) Probing GDK-Pixbuf loader modules...
(18/22) Compiling GSettings XML schema files...
(19/22) Update groovymame configuration
Welcome to Groovy Arcade Linux Setup
ERROR: If you run this script as root not through sudo, you must specify a user.
error: command failed to execute correctly
(20/22) Probing GTK3 input method modules...
(21/22) Updating icon theme caches...
(22/22) Updating the desktop file MIME type cache...

after upgrade,reboot system,cannot start Front-end ,Enter Desktop is black screen.

**Comment by substring** [comment]
Some people fixed it with rolling back mesa to 23.0.1 znd its llvm-libs at that moment

**Comment by mingkosan** [comment]
Can you give me some specific instructions? I have learned some Linux knowledge using this system, but it is still very limited. I am a staunch user of groovyarcade.

**Comment by substring** [comment]
sudo pacman -U https://archive.archlinux.org/packages/m/mesa/mesa-23.0.3-1-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/l/llvm-libs/llvm-libs-15.0.7-3-x86_64.pkg.tar.zst

**Comment by mingkosan** [comment]
It's true, I fixed it. It's amazing. Thank you very much
