### ISSUE TITLE
second start the computer no longer boots (HP Elitedesk 705 G3

### ISSUE THREAD

**Issue by Olsch69** [substring/os#46]
I have a HP Elitedesk 705 G3
On the first reboot everything works, on the second start the computer no longer boots and always shows me the error "boot device not found, Please install an operating system on you hard drive".
I don't know why the computer no longer wants to boot when I start it for the second time. I've already tried everything.

**Comment by substring** [comment]
Hi!

This reminds me some UEFI nightmares I had with some buggy bioses from HP. That was 2 years ago, I don't remember at all how I solved it, but it was just a matter of bios settings regarding either security, either UEFI , either something else. I will try to search

**Comment by substring** [comment]
So, from the messages I found that are 1.5 year old ... 2 solutions:
- have a script that always checks for GroovyArcade UEFI entry and eventually add it when the arcade user logs in. Could as well be a systemd shutdown service unit
- install on GA on the HDD but using a computer that supports booting on legacy and not UEFI. That's the way it ended for that other guy

**Comment by Olsch69** [comment]
Thanks for your answer.
I've made all the BIOS settings through at least 40 installations, even on an external USB stick, but never the same error.
The strange thing is that it boots up everything on the first reboot and from the second boot onwards it no longer finds a bootable hard drive.

**Comment by Olsch69** [comment]
I think the computer is booting from the wrong partition.
I can only select the drive as a boot option, which is normal, but if I go to boot options I still have the option to go to "Boot from file". Then "GABOOT,PciRoot(0x0)/Pci(0x11,0x0.) appears )/Sata(0x0,0x0/HD(1GPT,572E2005-A66D-488"
then I get to "\EFI\syslinux\syslinux.efi" when I start syslinux.efi GroovyArcade boots normally.
How do I get the computer to upload the file automatically?

**Comment by substring** [comment]
As I said : buggy bios. That's why I could only install on BIOS on another computer to boot in LEGACY, not UEFI

**Comment by Olsch69** [comment]
Ok i unterstand the Bios from HP is very buggy for GroovyArcade.
I'm not very familiar with Linux, is it perhaps possible to configure a USB stick that boots and executes the start command "\EFI\syslinux\syslinux.efi" from the partition ""GABOOT,PciRoot(0x0)/Pci(0x11, 0x0.) appears )/Sata(0x0,0x0/HD(1GPT,572E2005-A66D-488"
I think GrooyArcade is for me the best solution better than Grooymame  with Windows.

**Comment by Olsch69** [comment]
I tested Batocera and it also runs on Linux, so the computer starts up, but what does Batocera do differently when GroovyArcade starts up Linux

**Comment by substring** [comment]
Can you try `sudo efibootmgr --create --disk /dev/"$(lsblk -no PKNAME /dev/disk/by-label/GA)" --part 1 --loader /EFI/syslinux/syslinux.efi --label "GrovyArcade UEFI" --verbose -e 3` when you booted from the stick and tell me if the UEFI entry finally stays ? Do you have another EFI partition ?

**Comment by substring** [comment]
or alternatively, manual method from https://wiki.archlinux.org/title/GRUB#Default/fallback_boot_path adapted to syslinux

**Comment by Olsch69** [comment]
I'm coming home next week and will try it out straight away.
thanks for the help

**Comment by substring** [comment]
no news, closing
