### ISSUE TITLE
vertical monitor orientation not working

### ISSUE THREAD

**Issue by arfink** [substring/os#5]
Using the 2021.01 release: using gasetup to pick a vertical (or the rotating mode) monitor setting has no effect on attractmode or groovymame. All games will display in horizontal mode, even vertical ones.

**Comment by substring** [comment]
Weird, this has been tested and confirmed working ...

AM : not rotated, as rotation is a per layout setting, it's not attractmode-wide.

GM : damn, did I really forget to enable autoror ?

**Comment by substring** [comment]
fixed with gasetup 1.7.2
