### ISSUE TITLE
Boot groovyarcade failed after change the linux-15k to linux-lts-15khz

### ISSUE THREAD

**Issue by ekang4887** [substring/os#51]
When I change the linux-15K to linux-lts-15khz in gasetup. I reboot the ga,and the screen say:
loading  /vmlinuz-linux-lts-15khz:No such file or directory
boot:

after (boot: ) I can type word,but I dont know what can into the groovyarcade

Anyone can help me?thank you

**Comment by substring** [comment]
Hi,

Out of curiosity: booting with UEFI or legacy BIOS ?
I suggest you boot from the iso, log in to your GA install using the troubleshooting menu, run gasetup and select the normal kernel instead of lts

**Comment by ekang4887** [comment]
I have fix it ，I use a USB disk winpe os，and chang a backup syslinux.cfg with the new one,and the ga can boot into attact mode.
