### ISSUE TITLE
Install to Hard Drive Appears to Install Even if "Cancel" is Selected

### ISSUE THREAD

**Issue by oscilated** [substring/os#8]
I think this is just a visual issue, but if you select "Install to Hard Drive" and then select "Cancel", the installer appears to continue the installation.  In my particular case, I didn't have any storage device connected, other than the bootable USB, so I'm not sure where the installation was trying to write.  Fortunately my bootable USB continued to operate, so I don't think the installer tried to overwrite it.

**Comment by substring** [comment]
That's very true! Will fix this asap, thanks for reporting. I'll close the issue once gasetup is updated consequently

**Comment by substring** [comment]
Fixed with https://gitlab.com/groovyarcade/gasetup/-/commit/1b53b8b83727f5572d8c0822e9d59a046665932c
