### ISSUE TITLE
Network Setup Incorrectly Spells "Dynamic"

### ISSUE THREAD

**Issue by oscilated** [substring/os#9]
The network setup menu incorrectly spells "dynamic IP" as "dinamic IP".  No big deal, but wanted to point it out.  I know how sometimes having a TODO list makes it easier to get things accomplished.

**Comment by substring** [comment]
Part of what I want to remove ... but I ca fix a typo, yes ;)

**Comment by oscilated** [comment]
:)

**Comment by substring** [comment]
solved in gasetup 1.7.4, released with os 2021.03
